# This is a basic workflow that is manually triggered

name: Deploy to freedom

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          gatsby-args: --prefix-paths
        
    - name: List output files
      run: ls -laFG public/
      
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: public/
        remote_path: /var/www/yamazato/owc-2020
        remote_host: katayama.nuee.nagoya-u.ac.jp
        remote_user: yamazato
        remote_key: ${{ secrets.ID_ECDSA_FREEDOM }}
  
